packages:
  - packages/*
  - examples/*
  - docs

autoInstallPeers: false
linkWorkspacePackages: true

catalog:
  '@poppinss/dumper': 0.7.0
  '@tsdown/css': 0.22.14
  '@esotericsoftware/spine-core': 4.3.13
  '@esotericsoftware/spine-pixi-v8': 4.3.13
  '@ffmpeg-installer/ffmpeg': 1.1.0
  '@pmndrs/detect-gpu': 6.0.20
  '@types/howler': 2.2.13
  '@types/d3-shape': 3.2.0
  '@types/d3-scale': 4.0.9
  '@types/node': 26.2.0
  '@types/pako': 2.0.4
  acorn: 8.18.0
  acorn-walk: 8.3.4
  cheerio: 1.2.0
  commander: 15.0.0
  d3-shape: 3.2.0
  d3-scale: 4.0.2
  esbuild: 0.28.2
  fflate: 0.8.3
  free-tex-packer-core: 0.3.9
  hast-util-to-html: 9.0.5
  hastscript: 9.0.1
  happy-dom: 20.13.2
  howler: 2.2.4
  jsonc-parser: 3.3.1
  jiti: 2.7.0
  motion: 13.1.1
  open: 11.0.1
  pako: 2.1.0
  pixi.js: 8.20.1
  sass-embedded: 1.103.1
  sharp: 0.35.4
  subset-font: 2.5.0
  terser: 5.51.2
  tinyglobby: 0.2.17
  tsdown: 0.22.14
  typescript: 7.0.2
  vite: 8.2.1
  vitest: 4.1.10
  zod: 4.4.3

onlyBuiltDependencies:
  - '@ffmpeg-installer/darwin-arm64'
  - '@ffmpeg-installer/darwin-x64'
  - '@ffmpeg-installer/linux-arm'
  - '@ffmpeg-installer/linux-arm64'
  - '@ffmpeg-installer/linux-ia32'
  - '@ffmpeg-installer/linux-x64'
  - '@ffmpeg-installer/win32-ia32'
  - '@ffmpeg-installer/win32-x64'
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver
  - sharp
