const GENERATED_MODULE_HEADER = [
  '// AUTO-GENERATED FILE - DO NOT EDIT',
  '// Generated by @replayablejs/assets',
  '',
];

/**
 * Wraps generated TypeScript body lines in the shared module framing.
 *
 * Every generated module receives the same warning header, one blank line
 * before its body, and exactly one final newline. Callers provide only their
 * module-specific lines and do not need to know how generated files are
 * framed.
 *
 * @example
 *
 * ```ts
 * renderGeneratedModule(['export const sounds = {} as const;']);
 * ```
 *
 * returns:
 *
 * ```ts
 * // AUTO-GENERATED FILE - DO NOT EDIT
 * // Generated by @replayablejs/assets
 *
 * export const sounds = {} as const;
 * ```
 *
 * @param bodyLines - Complete source lines belonging after the shared header.
 * @returns A complete generated TypeScript module with one final newline.
 */
export function renderGeneratedModule(bodyLines: readonly string[]): string {
  return [...GENERATED_MODULE_HEADER, ...bodyLines, ''].join('\n');
}
