import { defineConfig } from 'vitepress';

const base = process.env.DOCS_BASE ?? '/';

export default defineConfig({
  base,
  // Generated by pages:build; ordinary docs builds do not require example exports.
  ignoreDeadLinks: [/^\/demos\/basic-(?:pixi-)?playable\.html$/],
  description: 'Open-source tooling for building compact, high-quality playable ads',
  lang: 'en-US',
  title: 'Replayable',
  head: [['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}replayable-logo.svg` }]],
  lastUpdated: true,
  themeConfig: {
    logo: { src: '/replayable-logo.svg', alt: 'Replayable' },
    search: { provider: 'local' },
    outline: { level: [2, 3] },
    editLink: {
      pattern: 'https://github.com/replayablejs/replayable/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026 Replayable contributors',
    },
    nav: [
      { link: '/guide/what-is-replayable', text: 'Guide' },
      { link: '/reference/cli', text: 'Reference' },
      {
        text: '0.1.0-alpha.1',
        items: [
          { text: 'About this release', link: '/guide/release-status' },
          { text: 'Releases', link: 'https://github.com/replayablejs/replayable/releases' },
          {
            text: 'Contributing',
            link: 'https://github.com/replayablejs/replayable/blob/main/CONTRIBUTING.md',
          },
        ],
      },
    ],
    sidebar: {
      '/guide/': [
        {
          items: [
            { link: '/guide/what-is-replayable', text: 'What is Replayable?' },
            { link: '/guide/getting-started', text: 'Getting Started' },
            { link: '/guide/build-and-export', text: 'Build and Export' },
            { link: '/guide/examples', text: 'Examples' },
          ],
          text: 'Introduction',
        },
        {
          text: 'Building a Playable',
          items: [
            { text: 'Project Configuration', link: '/reference/config' },
            { text: 'Asset Handling', link: '/reference/assets' },
            { text: 'Runtime and Lifecycle', link: '/reference/runtime' },
            { text: 'Pixi and Spine', link: '/reference/pixi' },
            { text: 'Animation', link: '/reference/tween' },
          ],
        },
      ],
      '/reference/': [
        {
          items: [
            { link: '/reference/cli', text: 'CLI' },
            { link: '/reference/config', text: 'Config' },
            { link: '/reference/runtime', text: 'Runtime' },
            { link: '/reference/canvas', text: 'Canvas' },
            { link: '/reference/pixi', text: 'Pixi' },
            { link: '/reference/tween', text: 'Tween' },
            { link: '/reference/devtools', text: 'Development tools' },
            { link: '/reference/build', text: 'Build' },
            { link: '/reference/export', text: 'Export' },
            {
              collapsed: false,
              items: [
                { link: '/reference/assets', text: 'Overview' },
                { link: '/reference/sprites', text: 'Sprites' },
                { link: '/reference/textures', text: 'Textures' },
                { link: '/reference/atlases', text: 'Atlases' },
                { link: '/reference/spines', text: 'Spines' },
                { link: '/reference/shaders', text: 'Shaders' },
                { link: '/reference/sounds', text: 'Sounds' },
                { link: '/reference/fonts', text: 'Fonts' },
                { link: '/reference/locales', text: 'Locales' },
              ],
              text: 'Assets',
            },
          ],
          text: 'Reference',
        },
      ],
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/replayablejs/replayable' }],
  },
});
