import sharp from 'sharp';
import { describe, expect, it } from 'vitest';
import { z } from 'zod';

import { buildAssets } from '../../src/index.js';
import { config } from '../support/config.js';
import { createTestProject } from '../support/test-project.js';

describe('atlases', () => {
  it('packs image directories into deterministic Pixi atlases', async () => {
    const project = await createTestProject();
    await project.directory('assets/source/atlases/ui');
    await Promise.all([
      sharp({ create: { background: 'red', channels: 4, height: 3, width: 4 } })
        .png()
        .toFile(project.path('assets/source/atlases/ui/button.png')),
      sharp({ create: { background: 'blue', channels: 4, height: 2, width: 2 } })
        .png()
        .toFile(project.path('assets/source/atlases/ui/icon.png')),
    ]);

    const result = await buildAssets(
      config({
        assets: {
          atlases: [
            {
              match: 'ui',
              options: { allowRotation: false, powerOfTwo: false },
            },
            {
              match: 'ui',
              options: { allowRotation: false, powerOfTwo: true },
            },
          ],
        },
        emit: {
          assets: 'src/assets/assets.gen.ts',
          registries: 'src/assets/registries',
        },
      }),
      project.root,
    );
    const atlas = z
      .object({
        frames: z.record(z.string(), z.unknown()),
        meta: z.object({ size: z.object({ h: z.number(), w: z.number() }) }),
      })
      .parse(JSON.parse(await project.readText('assets/generated/atlases/ui/ui.json')));
    const generated = await project.readText('src/assets/assets.gen.ts');
    const registry = await project.readText('src/assets/registries/atlases.ts');
    const emittedFiles = await project.entries('assets/generated/atlases/ui');

    expect(result).toMatchObject({ emittedAssets: 1, emittedFiles: 2 });
    expect(emittedFiles.filter((file) => !file.endsWith('.json'))).toHaveLength(1);
    expect(Object.keys(atlas.frames).sort()).toEqual(['button', 'icon']);
    expect(isPowerOfTwo(atlas.meta.size.w)).toBe(true);
    expect(isPowerOfTwo(atlas.meta.size.h)).toBe(true);
    expect(generated).toMatch(/"ui": \{ json: atlas_\d+, image: image_\d+ \}/);
    expect(generated.match(/import image_/g)).toHaveLength(1);
    expect(registry).toMatchInlineSnapshot(`
      "// AUTO-GENERATED FILE - DO NOT EDIT
      // Generated by @replayablejs/assets

      export const atlases = {
        "ui": {
          "button": "button",
          "icon": "icon"
        }
      } as const;
      "
    `);
  });
});

function isPowerOfTwo(value: number): boolean {
  return value > 0 && (value & (value - 1)) === 0;
}
