import { describe, expect, it } from 'vitest';

import { assetCategories, buildAssets } from '../../src/index.js';
import { writeCompleteBuildFixture } from '../support/complete-build-fixture.js';
import { config } from '../support/config.js';
import { createTestProject, type TestProject } from '../support/test-project.js';

describe('complete asset build', () => {
  it('builds every category into deterministic resources, assets, and registries', async () => {
    const project = await createTestProject();
    await writeCompleteBuildFixture(project);
    const assetConfig = config({
      assets: {
        atlases: [{}],
        fonts: [{ options: { family: 'Replayable Body' } }],
        locales: [{}],
        shaders: [{}],
        sounds: [{}],
        spines: [{}],
        sprites: [{}],
        textures: [{ options: { lossless: true } }],
      },
      bundles: {
        secondary: { include: ['sounds/theme', 'spines/hero'] },
      },
      emit: {
        assets: 'src/assets/assets.ts',
        registries: 'src/assets/registries',
      },
      outDir: 'src/assets/resources',
    });

    const firstResult = await buildAssets(assetConfig, project.root);
    const firstOutput = await captureGeneratedOutput(project);

    expect(firstResult).toEqual({
      bundles: ['primary', 'secondary'],
      emittedAssets: 8,
      emittedFiles: 12,
      outputDirectory: project.path('src/assets/resources'),
    });
    expect(firstOutput.resources).toEqual([
      'atlases/interface/interface.json',
      expect.stringMatching(/^atlases\/interface\/interface\.(?:avif|jpg|png|webp)$/),
      'fonts/body.woff2',
      'locales/translations.json',
      'shaders/grayscale/frag.glsl',
      'shaders/grayscale/vert.glsl',
      expect.stringMatching(/^sounds\/theme\.(?:m4a|mp3)$/),
      'spines/hero/atlas.atlas',
      expect.stringMatching(/^spines\/hero\/images\/page0\.(?:avif|jpg|png|webp)$/),
      'spines/hero/skeleton.json',
      expect.stringMatching(/^sprites\/logo\.(?:avif|jpg|png|webp)$/),
      expect.stringMatching(/^textures\/noise\.(?:png|webp)$/),
    ]);
    expect(firstOutput.registries.sounds).toMatchInlineSnapshot(`
      "// AUTO-GENERATED FILE - DO NOT EDIT
      // Generated by @replayablejs/assets

      export const sounds = {
        "theme": "theme"
      } as const;
      "
    `);

    const secondResult = await buildAssets(assetConfig, project.root);
    const secondOutput = await captureGeneratedOutput(project);

    expect(secondResult).toEqual(firstResult);
    expect(secondOutput).toEqual(firstOutput);
  });
});

interface GeneratedOutput {
  readonly assets: string;
  readonly registries: Readonly<Record<string, string>>;
  readonly resources: readonly string[];
}

/** Captures every deterministic build product while ignoring encoded binary contents. */
async function captureGeneratedOutput(project: TestProject): Promise<GeneratedOutput> {
  const registryEntries = await Promise.all(
    assetCategories.map(async (category) => [
      category,
      await project.readText(`src/assets/registries/${category}.ts`),
    ]),
  );

  return {
    assets: await project.readText('src/assets/assets.ts'),
    registries: Object.fromEntries(registryEntries),
    resources: (await project.files('src/assets/resources')).sort(),
  };
}
