import { readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { buildAssets } from '../../src/index.js';
import { config } from '../support/config.js';
import { createTestProject } from '../support/test-project.js';

describe('fonts', () => {
  it('subsets fonts and emits their required runtime families', async () => {
    const project = await createTestProject();
    const subsetFontEntry = fileURLToPath(import.meta.resolve('subset-font'));
    const fixture = resolve(dirname(subsetFontEntry), '../fontverter/testdata/Roboto-400.ttf');
    const fixtureContents = await readFile(fixture);
    await Promise.all([
      project.write('assets/source/fonts/ui.ttf', fixtureContents),
      project.write('assets/source/fonts/body.ttf', fixtureContents),
    ]);

    const result = await buildAssets(
      config({
        assets: {
          fonts: [
            {
              match: '**/*.ttf',
              options: { family: 'Replayable Body' },
            },
            {
              match: 'ui.ttf',
              options: {
                extraCharacters: '֏',
                family: 'Replayable UI',
              },
            },
          ],
        },
        emit: {
          assets: 'src/assets/assets.gen.ts',
          registries: 'src/assets/registries',
        },
      }),
      project.root,
    );
    const generated = await project.readText('src/assets/assets.gen.ts');
    const registry = await project.readText('src/assets/registries/fonts.ts');
    const uiSubset = await project.readBytes('assets/generated/fonts/ui.woff2');
    const bodySubset = await project.readBytes('assets/generated/fonts/body.woff2');

    expect(result.emittedAssets).toBe(2);
    expect(uiSubset.subarray(0, 4).toString('ascii')).toBe('wOF2');
    expect(bodySubset.subarray(0, 4).toString('ascii')).toBe('wOF2');
    await expect(project.readBytes('assets/generated/fonts/ui.woff')).rejects.toMatchObject({
      code: 'ENOENT',
    });
    expect(generated).toMatch(/"body": \{ src: font_\d+, family: "Replayable Body" \},/);
    expect(generated).toMatch(/"ui": \{ src: font_\d+, family: "Replayable UI" \},/);
    expect(registry).toMatchInlineSnapshot(`
      "// AUTO-GENERATED FILE - DO NOT EDIT
      // Generated by @replayablejs/assets

      export const fonts = {
        "Replayable Body": "Replayable Body",
        "Replayable UI": "Replayable UI"
      } as const;
      "
    `);
  });
});
