import { describe, expect, it } from 'vitest';

import { buildAssets } from '../../src/index.js';
import { config } from '../support/config.js';
import { createTestProject } from '../support/test-project.js';

describe('registries', () => {
  it('emits every typed registry and removes stale registry files', async () => {
    const project = await createTestProject();
    await project.write('assets/source/locales/translations.jsonc', '{"play":{"en":"Play"}}');
    await project.write('src/assets/registries/stale.ts', 'stale');

    await buildAssets(
      config({
        emit: {
          assets: 'src/assets/assets.gen.ts',
          registries: 'src/assets/registries',
        },
      }),
      project.root,
    );
    const locales = await project.readText('src/assets/registries/locales.ts');
    const sounds = await project.readText('src/assets/registries/sounds.ts');
    const index = await project.readText('src/assets/registries/index.ts');

    expect(locales).toMatchInlineSnapshot(`
      "// AUTO-GENERATED FILE - DO NOT EDIT
      // Generated by @replayablejs/assets

      export const locales = {
        "play": "play"
      } as const;
      "
    `);
    expect(sounds).toMatchInlineSnapshot(`
      "// AUTO-GENERATED FILE - DO NOT EDIT
      // Generated by @replayablejs/assets

      export const sounds = {} as const;
      "
    `);
    expect(index).toMatchInlineSnapshot(`
      "// AUTO-GENERATED FILE - DO NOT EDIT
      // Generated by @replayablejs/assets

      export { sprites } from './sprites.js';
      export { textures } from './textures.js';
      export { sounds } from './sounds.js';
      export { fonts } from './fonts.js';
      export { locales } from './locales.js';
      export { atlases } from './atlases.js';
      export { spines } from './spines.js';
      export { shaders } from './shaders.js';
      "
    `);

    expect((await project.files('src/assets/registries')).sort()).toEqual([
      'atlases.ts',
      'fonts.ts',
      'index.ts',
      'locales.ts',
      'shaders.ts',
      'sounds.ts',
      'spines.ts',
      'sprites.ts',
      'textures.ts',
    ]);

    await expect(project.readBytes('src/assets/registries/stale.ts')).rejects.toMatchObject({
      code: 'ENOENT',
    });
  });
});
