import { describe, expect, it } from 'vitest';

import { buildAssets } from '../../src/index.js';
import { config } from '../support/config.js';
import { createTestProject } from '../support/test-project.js';

describe('shaders', () => {
  it('copies shader pairs without imposing a GLSL version', async () => {
    const project = await createTestProject();
    await project.write('assets/source/shaders/effects/grayscale/vert.glsl', 'in vec2 aPosition;');
    await project.write(
      'assets/source/shaders/effects/grayscale/frag.glsl',
      'precision mediump float; out vec4 outColor;',
    );

    const result = await buildAssets(
      config({
        assets: { shaders: [{}] },
        emit: {
          assets: 'src/assets/assets.gen.ts',
          registries: 'src/assets/registries',
        },
      }),
      project.root,
    );
    const generated = await project.readText('src/assets/assets.gen.ts');
    const registry = await project.readText('src/assets/registries/shaders.ts');
    const fragment = await project.readText('assets/generated/shaders/effects/grayscale/frag.glsl');

    expect(result).toMatchObject({ emittedAssets: 1, emittedFiles: 2 });
    expect(generated).toMatch(/"effects\/grayscale": \{ vert: shader_\d+, frag: shader_\d+ \},/);
    expect(fragment).toBe('precision mediump float; out vec4 outColor;');
    expect(registry).toMatchInlineSnapshot(`
      "// AUTO-GENERATED FILE - DO NOT EDIT
      // Generated by @replayablejs/assets

      export const shaders = {
        "effects/grayscale": "effects/grayscale"
      } as const;
      "
    `);
  });
});
