import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

import type { AssetBundle, AssetGroups } from '#types/asset-groups.js';
import { assetCategories, type AssetCategory } from '#types/categories.js';
import type { AssetsModuleContext, GeneratedImport } from '#types/emission.js';
import type { ProcessedAsset } from '#types/processed-assets.js';

import { renderAtlasEntry } from './categories/atlas.js';
import { renderFontEntry } from './categories/font.js';
import { renderImageEntry } from './categories/image.js';
import { renderLocaleEntry } from './categories/locale.js';
import { renderShaderEntry } from './categories/shader.js';
import { renderSoundEntry } from './categories/sound.js';
import { renderSpineEntry } from './categories/spine.js';
import { renderGeneratedModule } from './utils/generated-module.js';

/**
 * Generates the TypeScript module consumed by a playable at runtime.
 *
 * Processed assets already represent complete runtime values. This emitter
 * renders those values into an in-memory module and then performs one
 * filesystem write. Category renderers never write files themselves.
 *
 * Every example in this file follows the same build: bundle `primary` contains
 * the sound `click` and the two-page Spine asset `hero`; bundle `secondary`
 * contains the sprite `logo`.
 *
 * @example
 *
 * ```ts
 * const assetGroups = groupAssets([
 *   {
 *     bundle: 'primary',
 *     category: 'sounds',
 *     id: 'click',
 *     file: {
 *       format: 'm4a',
 *       path: '/project/assets/generated/sounds/click.m4a',
 *     },
 *   },
 *   {
 *     bundle: 'primary',
 *     category: 'spines',
 *     id: 'hero',
 *     files: {
 *       skeleton: {
 *         format: 'json',
 *         path: '/project/assets/generated/spines/hero/skeleton.json',
 *       },
 *       atlas: {
 *         format: 'atlas',
 *         path: '/project/assets/generated/spines/hero/atlas.atlas',
 *       },
 *       images: [
 *         {
 *           format: 'webp',
 *           path: '/project/assets/generated/spines/hero/images/page0.webp',
 *         },
 *         {
 *           format: 'avif',
 *           path: '/project/assets/generated/spines/hero/images/page1.avif',
 *         },
 *       ],
 *     },
 *     runtime: { scale: 0.5 },
 *   },
 *   {
 *     bundle: 'secondary',
 *     category: 'sprites',
 *     id: 'logo',
 *     file: {
 *       format: 'webp',
 *       path: '/project/assets/generated/sprites/logo.webp',
 *     },
 *     runtime: { scale: 1 },
 *   },
 * ]);
 *
 * await emitAssetsModule('/project/src/assets/assets.gen.ts', assetGroups);
 * ```
 *
 * The call writes `/project/src/assets/assets.gen.ts` with the complete source
 * shown in the `renderAssetsModule` example below.
 */
export async function emitAssetsModule(file: string, assetGroups: AssetGroups): Promise<void> {
  const source = renderAssetsModule(assetGroups, dirname(file));

  await writeAssetsModule(file, source);
}

/**
 * Renders every processed asset into the complete generated TypeScript module.
 *
 * `assetGroups` contains the canonical bundle, category, and asset hierarchy
 * prepared for all emitters. `fromDirectory` is the directory that will contain
 * the generated module; import registration uses it to turn absolute generated-
 * file paths into relative module specifiers.
 *
 * The function traverses every prepared bundle and renders its nested category
 * and asset entries. Rendering an entry registers its physical files in a
 * local `AssetsModuleContext`, so bundle lines must be rendered before import
 * statements can be assembled. The context never escapes this function.
 *
 * Given the three canonical processed records above and
 * `fromDirectory = '/project/src/assets'`, the function returns this complete
 * string. Bundle order, category order, asset order, and module-wide import
 * numbering are all visible in the result:
 *
 * ```ts
 * // AUTO-GENERATED FILE - DO NOT EDIT
 * // Generated by @replayablejs/assets
 *
 * import type { Assets } from '@replayablejs/assets';
 * import sound_0 from '../../assets/generated/sounds/click.m4a';
 * import spine_1 from '../../assets/generated/spines/hero/skeleton.json';
 * import spine_2 from '../../assets/generated/spines/hero/atlas.atlas';
 * import image_3 from '../../assets/generated/spines/hero/images/page0.webp';
 * import image_4 from '../../assets/generated/spines/hero/images/page1.avif';
 * import image_5 from '../../assets/generated/sprites/logo.webp';
 *
 * export const assets = {
 *   "primary": {
 *     sounds: {
 *       "click": sound_0,
 *     },
 *     spines: {
 *       "hero": { format: "json", skel: spine_1, atlas: spine_2, images: [image_3, image_4], scale: 0.5 },
 *     },
 *   },
 *   "secondary": {
 *     sprites: {
 *       "logo": { src: image_5, scale: 1 },
 *     },
 *   },
 * } satisfies Assets;
 * ```
 *
 * This function only returns source text. It does not create directories or
 * write the generated module.
 *
 * @param assetGroups - Processed assets organized once for all emitters.
 * @param fromDirectory - Absolute directory containing the generated module.
 * @returns The complete TypeScript module, including imports and final newline.
 */
function renderAssetsModule(assetGroups: AssetGroups, fromDirectory: string): string {
  const imports: GeneratedImport[] = [];
  const context = { fromDirectory, imports } satisfies AssetsModuleContext;
  const bundleLines = assetGroups.bundles.flatMap((bundle) => renderBundle(bundle, context));
  const importLines = imports.map(
    (generatedImport) =>
      `import ${generatedImport.name} from ${JSON.stringify(generatedImport.path)};`,
  );

  return renderGeneratedModule([
    "import type { Assets } from '@replayablejs/assets';",
    ...importLines,
    '',
    'export const assets = {',
    ...bundleLines,
    '} satisfies Assets;',
  ]);
}

/**
 * Renders one bundle object containing each of its non-empty categories.
 *
 * The caller supplies one bundle whose assets are already separated by category
 * and sorted by ID. This function visits categories in the canonical
 * `assetCategories` order and delegates each non-empty block to
 * `renderCategory`. Entry rendering may register imports in `context`, but this
 * function returns only the lines belonging inside the top-level `assets`
 * object.
 *
 * In the canonical example, calling this function for `primary` with the
 * `click` and `hero` records returns the complete bundle block below. Because
 * the shared context is initially empty, rendering the block also registers
 * `sound_0`, `spine_1`, `spine_2`, `image_3`, and `image_4` in that order:
 *
 * ```ts
 * [
 *   '  "primary": {',
 *   '    sounds: {',
 *   '      "click": sound_0,',
 *   '    },',
 *   '    spines: {',
 *   '      "hero": { format: "json", skel: spine_1, atlas: spine_2, images: [image_3, image_4], scale: 0.5 },',
 *   '    },',
 *   '  },',
 * ]
 * ```
 *
 * @param bundle - Organized runtime bundle to render.
 * @param context - Module-wide state that receives imports from rendered entries.
 * @returns Source lines for one complete bundle object property.
 */
function renderBundle(bundle: AssetBundle, context: AssetsModuleContext): string[] {
  const categoryLines = assetCategories.flatMap((category) =>
    renderCategory(category, bundle.categories[category], context),
  );

  return [`  ${JSON.stringify(bundle.name)}: {`, ...categoryLines, '  },'];
}

/**
 * Renders one category block from the matching assets in a bundle.
 *
 * `categoryAssets` contains only the requested category and is already sorted
 * by runtime ID. This function asks `renderAssetEntry` for one property line per
 * record and wraps those lines in the category object.
 *
 * In the canonical example, calling the function with `category = 'sounds'`
 * and the prepared `[click]` group registers its M4A file as `sound_0` and
 * returns:
 *
 * ```ts
 * [
 *   '    sounds: {',
 *   '      "click": sound_0,',
 *   '    },',
 * ]
 * ```
 *
 * A bundle without assets in the requested category returns `[]`, so no empty
 * category object is written to the generated module.
 *
 * @param category - Category to select and use as the generated object key.
 * @param categoryAssets - Prepared assets belonging to this exact category.
 * @param context - Module-wide state that receives imports from rendered entries.
 * @returns A complete category block, or an empty array when the category is absent.
 */
function renderCategory(
  category: AssetCategory,
  categoryAssets: readonly ProcessedAsset[],
  context: AssetsModuleContext,
): string[] {
  if (categoryAssets.length === 0) {
    return [];
  }

  const entryLines = categoryAssets.map((asset) => renderAssetEntry(asset, context));

  return [`    ${category}: {`, ...entryLines, '    },'];
}

/**
 * Renders one processed asset as one property inside its category object.
 *
 * `ProcessedAsset` is a discriminated union. Switching on `asset.category`
 * narrows the record to the exact type required by its specialized renderer.
 * Those renderers register all physical files owned by the asset in `context`
 * and return one already-indented TypeScript property line.
 *
 * In the canonical example, the first call receives the complete `click`
 * record, including its bundle, runtime ID, and selected audio file:
 *
 * ```ts
 * {
 *   bundle: 'primary',
 *   category: 'sounds',
 *   id: 'click',
 *   file: {
 *     format: 'm4a',
 *     path: '/project/assets/generated/sounds/click.m4a',
 *   },
 * }
 * ```
 *
 * Rendering it registers the selected M4A file as `sound_0` and returns:
 *
 * ```ts
 * '      "click": sound_0,'
 * ```
 *
 * The next call receives the complete two-page `hero` record from the same
 * `primary` bundle:
 *
 * ```ts
 * {
 *   bundle: 'primary',
 *   category: 'spines',
 *   id: 'hero',
 *   files: {
 *     skeleton: {
 *       format: 'json',
 *       path: '/project/assets/generated/spines/hero/skeleton.json',
 *     },
 *     atlas: {
 *       format: 'atlas',
 *       path: '/project/assets/generated/spines/hero/atlas.atlas',
 *     },
 *     images: [
 *       {
 *         format: 'webp',
 *         path: '/project/assets/generated/spines/hero/images/page0.webp',
 *       },
 *       {
 *         format: 'avif',
 *         path: '/project/assets/generated/spines/hero/images/page1.avif',
 *       },
 *     ],
 *   },
 *   runtime: { scale: 0.5 },
 * }
 * ```
 *
 * Because `click` already registered `sound_0`, rendering `hero` registers
 * `spine_1`, `spine_2`, `image_3`, and `image_4`, then returns exactly one
 * property line:
 *
 * ```ts
 * '      "hero": { format: "json", skel: spine_1, atlas: spine_2, images: [image_3, image_4], scale: 0.5 },'
 * ```
 *
 * The renderer therefore returns one line per logical asset, not one line per
 * generated file.
 *
 * @param asset - One complete logical runtime asset from processing.
 * @param context - Module-wide state used to register the asset's files.
 * @returns One indented TypeScript property line for the asset.
 */
function renderAssetEntry(asset: ProcessedAsset, context: AssetsModuleContext): string {
  switch (asset.category) {
    case 'atlases':
      return renderAtlasEntry(asset, context);
    case 'fonts':
      return renderFontEntry(asset, context);
    case 'locales':
      return renderLocaleEntry(asset, context);
    case 'shaders':
      return renderShaderEntry(asset, context);
    case 'sounds':
      return renderSoundEntry(asset, context);
    case 'spines':
      return renderSpineEntry(asset, context);
    case 'sprites':
    case 'textures':
      return renderImageEntry(asset, context);
    default:
      return asset satisfies never;
  }
}

/**
 * Writes one fully rendered assets module to its final destination.
 *
 * In the canonical example, `file` is
 * `/project/src/assets/assets.gen.ts` and `source` is the complete module string
 * returned by `renderAssetsModule`. The function creates
 * `/project/src/assets` when necessary and writes that string unchanged to
 * `assets.gen.ts`. It performs no rendering, formatting, or additional import
 * discovery and resolves without a return value after the write completes.
 *
 * @param file - Absolute destination of the generated TypeScript module.
 * @param source - Complete module source returned by `renderAssetsModule`.
 * @returns A promise that resolves after the module has been written.
 */
async function writeAssetsModule(file: string, source: string): Promise<void> {
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, source);
}
