import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import type { AssetGroups, AssetsByCategory } from '#types/asset-groups.js';
import { assetCategories, type AssetCategory } from '#types/categories.js';
import type { RenderedRegistryModule } from '#types/emission.js';
import type { RegistryObject } from '#types/emission.js';

import { renderAtlasRegistry } from './categories/atlas.js';
import { renderFontRegistry } from './categories/font.js';
import { renderImageRegistry } from './categories/image.js';
import { renderLocaleRegistry } from './categories/locale.js';
import { renderShaderRegistry } from './categories/shader.js';
import { renderSoundRegistry } from './categories/sound.js';
import { renderSpineRegistry } from './categories/spine.js';
import { renderGeneratedModule } from './utils/generated-module.js';
import { renderRegistryObject } from './utils/object-literal.js';

/**
 * Emits one bundle-independent registry module per supported category and one index.
 *
 * Rendering first produces every complete module in memory. Writing then owns
 * directory creation and filesystem output. Keeping those phases separate
 * prevents partial rendering logic from being mixed with filesystem work.
 *
 * Every build with registry emission enabled creates the complete registry set:
 *
 * ```text
 * registries/
 *   atlases.ts
 *   fonts.ts
 *   locales.ts
 *   shaders.ts
 *   sounds.ts
 *   spines.ts
 *   sprites.ts
 *   textures.ts
 *   index.ts
 * ```
 *
 * Empty categories still receive an empty module, keeping generated imports
 * stable. The canonical `assetCategories` order determines file creation and
 * index exports.
 *
 * @param directory - Absolute directory that will contain generated registries.
 * @param assetGroups - Processed assets organized once for all emitters.
 */
export async function emitRegistries(directory: string, assetGroups: AssetGroups): Promise<void> {
  const modules = renderRegistryModules(assetGroups);

  await writeRegistryModules(directory, modules);
}

/**
 * Renders every category registry and the re-exporting index in memory.
 *
 * Every supported category reads its complete bundle-independent bucket and
 * produces one module, including categories with no assets. The index is added
 * last so the returned array mirrors the intended write order.
 *
 * For a build containing only the sound `click`, the returned array still
 * contains one module for every supported category plus `index.ts`. Its sound
 * item is:
 *
 * ```ts
 * {
 *   filename: 'sounds.ts',
 *   source: `// AUTO-GENERATED FILE - DO NOT EDIT
 * // Generated by @replayablejs/assets
 *
 * export const sounds = {
 *   "click": "click"
 * } as const;
 * `,
 * }
 * ```
 *
 * @param assetGroups - Processed assets organized once for all emitters.
 * @returns Complete registry modules ready to be written without further rendering.
 */
function renderRegistryModules(assetGroups: AssetGroups): RenderedRegistryModule[] {
  const categoryRegistryModules = assetCategories.map((category) =>
    renderRegistryModule(category, assetGroups.categories),
  );

  const registryIndexModule = {
    filename: 'index.ts',
    source: renderRegistryIndex(),
  };

  return [...categoryRegistryModules, registryIndexModule];
}

/**
 * Writes already-rendered registry modules into one generated directory.
 *
 * This function performs no grouping, category dispatch, or serialization. It
 * creates the destination directory and writes modules in the order supplied
 * by `renderRegistryModules`.
 *
 * @param directory - Absolute directory that will contain generated registries.
 * @param modules - Complete filenames and sources produced during rendering.
 */
async function writeRegistryModules(
  directory: string,
  modules: readonly RenderedRegistryModule[],
): Promise<void> {
  await mkdir(directory, { recursive: true });

  for (const module of modules) {
    await writeFile(resolve(directory, module.filename), module.source);
  }
}

/**
 * Renders one complete bundle-independent registry module for a category.
 *
 * Category buckets are already combined and ordered by the pipeline. This
 * function delegates the category-specific data shape to
 * `renderCategoryRegistry`, then owns the generated TypeScript module around
 * that value.
 *
 * For category `sounds` and rendered registry data
 * `{ click: 'click' }`, the complete return value is:
 *
 * ```ts
 * {
 *   filename: 'sounds.ts',
 *   source: `// AUTO-GENERATED FILE - DO NOT EDIT
 * // Generated by @replayablejs/assets
 *
 * export const sounds = {
 *   "click": "click"
 * } as const;
 * `,
 * }
 * ```
 *
 * @param category - Category used for bucket selection and the exported name.
 * @param assets - All processed assets grouped by category across the build.
 * @returns One complete generated category registry module.
 */
function renderRegistryModule(
  category: AssetCategory,
  assets: AssetsByCategory,
): RenderedRegistryModule {
  const registry = renderCategoryRegistry(category, assets);
  const source = renderGeneratedModule([
    `export const ${category} = ${renderRegistryObject(registry)} as const;`,
  ]);

  return { filename: `${category}.ts`, source };
}

/**
 * Selects the concrete registry renderer for one typed category bucket.
 *
 * `AssetsByCategory` preserves the relationship between every category name and
 * its processed asset type. The switch therefore passes atlas assets to the
 * atlas renderer, font assets to the font renderer, and so on without filtering
 * or type assertions. Sprites and textures intentionally share the image
 * registry representation.
 *
 * @param category - Category whose registry should be rendered.
 * @param assets - All typed category buckets across the complete build.
 * @returns The rendered registry for the populated category bucket.
 */
function renderCategoryRegistry(category: AssetCategory, assets: AssetsByCategory): RegistryObject {
  switch (category) {
    case 'atlases':
      return renderAtlasRegistry(assets.atlases);
    case 'fonts':
      return renderFontRegistry(assets.fonts);
    case 'locales':
      return renderLocaleRegistry(assets.locales);
    case 'shaders':
      return renderShaderRegistry(assets.shaders);
    case 'sounds':
      return renderSoundRegistry(assets.sounds);
    case 'spines':
      return renderSpineRegistry(assets.spines);
    case 'sprites':
      return renderImageRegistry(assets.sprites);
    case 'textures':
      return renderImageRegistry(assets.textures);
    default:
      return category satisfies never;
  }
}

/**
 * Serializes the index that re-exports every generated category registry.
 *
 * Given the canonical asset categories, the returned module contains the
 * complete registry set in canonical order:
 *
 * ```ts
 * // AUTO-GENERATED FILE - DO NOT EDIT
 * // Generated by @replayablejs/assets
 *
 * export { sprites } from './sprites.js';
 * export { textures } from './textures.js';
 * export { sounds } from './sounds.js';
 * export { fonts } from './fonts.js';
 * export { locales } from './locales.js';
 * export { atlases } from './atlases.js';
 * export { spines } from './spines.js';
 * export { shaders } from './shaders.js';
 * ```
 *
 * @returns The complete generated index source, including its final newline.
 */
function renderRegistryIndex(): string {
  return renderGeneratedModule([
    ...assetCategories.map((category) => `export { ${category} } from './${category}.js';`),
  ]);
}
